/**
 *
 * Global action types are defined here.
 * DONOT change this file
 */

// Initial provider
export const SET_PARTNER_DETAILS = "SET_PARTNER_DETAILS"
export const UPDATE_AUTH_STATUS = "UPDATE_AUTH_STATUS"
export const UPDATE_NET_STATUS = "UPDATE_NET_STATUS"
export const UPDATE_API_STATUS = "UPDATE_API_STATUS"
export const TOGGLE_KEYBOARD_SHORT_VIEW = "TOGGLE_KEYBOARD_SHORT_VIEW"
export const FILE_UPLOAD_VIEW = "FILE_UPLOAD_VIEW"
export const TOGGLE_FLASH_NEWS_LIST_VIEW = "TOGGLE_FLASH_NEWS_LIST_VIEW"
export const TOGGLE_TICKET_BULK_OPTIONS = "TOGGLE_TICKET_BULK_OPTIONS"
export const TOGGLE_TICKET_MULTI_LINE = "TOGGLE_TICKET_MULTI_LINE"
export const TOGGLE_AGENT_CO_PILOT = "TOGGLE_AGENT_CO_PILOT"
//  Multi-Language:
export const GET_LANG = "GET_LANG"
export const LOAD_LITERALS = "LOAD_LITERALS"
export const SET_LANG = "SET_LANG"

export const SET_FCM_CONN_STATUS = "SET_FCM_CONN_STATUS"

// pin and unpin
export const TOGGLE_TICKET_DETAILS_PIN_AND_UNPIN = "TOGGLE_TICKET_DETAILS_PIN_AND_UNPIN"
export const DEFAULT_PINNED_TICKET_DETAILS = "DEFAULT_PINNED_TICKET_DETAILS"
